application: nearbylink
version: 1-3
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /apple-touch-icon.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png

- url: /dashboard/.*
  script: main.py
  login: required

- url: .*
  script: main.py
